(write (or))
(newline)
(write (or #f #f #f 1))
(newline)
(write (or 1 2 3 4))
(newline)
(write (or #f #f #t 2))
(newline)
(write (and))
(newline)
(write (and #f 1 2 3))
(newline)
(write (and '() 2 3))
(newline)
(write (and (or #t #f #t #f) #t #t #f))
(newline)

