(write (if #t 0 1))
(newline)
(write (if #f 0 1))
(newline)
(if 0 (write 0) (write 1))
(newline)
(if '() (write 0) (write 1))
(newline)
(if #f (write 0) (write 1))
(newline)
(if (< 5 1) (write 0) (write 1))
(newline)
(write (if (= 2 3) (write 0) (write 1)))
(newline)
(write (if (not (= 1 1)) 10 20))
(newline)
